title: Play by Post mapping
author: Beau Tremblay
email: beau.tremblay@gmail.com
description: 
  An exploration of using GitHub pages to handle mapping for play
  by post encounters.
  
theme: jekyll-theme-architect
